### PR TITLE
Updated #4 to a more understandable solution.

### PR DESCRIPTION
**Pull request by NikhilCodes**

### CODE REVIEW

**Comment by r1cc4rdo** [comment]
Hi there!
Thank you for the PR :) Not going to pull as it stands because your solution does not have constant space complexity as the problem requires.

Mine does not either to be fully honest -- the intended solution is an in-place bucket sort with size 1 bins, which back then I was too lazy to implement. Will probably give it a second go now that you've drawn my attention to it :)

**Comment by r1cc4rdo** [comment]
I've updated the solution to #4, see if it makes sense to you.
I've left there, commented, both our previous solutions.

**Comment by NikhilCodes** [comment]
> I've updated the solution to #4, see if it makes sense to you.
> I've left there, commented, both our previous solutions.

Nice One!
But I'm worried about the nested while loop which might throw out O(n) time complexity.
Thanks for mentioning my solution.

**Comment by r1cc4rdo** [comment]
Closing the PR. Thanks!

**Pull request closed without merging**
