### PR TITLE
Solution to Problem 4

### PR DESCRIPTION
**Pull request by vaibhavpandey11**
This solution is taken from https://github.com/vaibhavpandey11

### CODE REVIEW

**Comment by r1cc4rdo** [comment]
My solution for problem 4 is here: [r1cc4rdo/daily_coding_problem/solution_04.py](https://github.com/r1cc4rdo/daily_coding_problem/blob/master/problems/04/solution_04.py)
Anything wrong with it?

Also, note that your solution is not constant space as the problem requires.
See [this stackoverflow post](https://stackoverflow.com/questions/48759175/what-is-the-space-complexity-of-the-python-sort/48759241)

**Comment by vaibhavpandey11** [comment]
I am really sorry.
Actually, I am a student of B.Tech 1st year and I have been taught Python
in my college. I found many problems of dailycodingproblem and started
solving them for practice. And I thought how can I get "Stars" on my
repository. So I started to pull requests.

I am new to these repositories and I don't know much about Github.
And I admit that I don't know much about time and space complexity as well.

Really sorry, if I disturbed you.
Pardon me.

**Comment by r1cc4rdo** [comment]
Hey, no problem man :)
I'm afraid the only recipe for getting stars is to put out content good enough for others to like.
Not that I necessarily think amassing internet points is a worthwhile goal though ;)

Pull requests (PRs) are for contributing to a project. Typically, you fork a project, solve some outstanding problem or improve something, and ask the original owner to include your changes in the original repository (hence, Pull Request).

Closing this one now. Take care!

**Comment by vaibhavpandey11** [comment]
Thanks for your kind advice. I will definitely follow this in future.

Thank you.

**Pull request closed without merging**
